#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

mkdir -p $HOME/.config/clangd/

install_config clangd.yaml .config/clangd/config.yaml
install_config clang-format.yaml .clang-format
