
[window]
dimensions = { columns = 80, lines = 24 }
position = "None"
padding = { x = 0, y = 0 }
dynamic_padding = true  # spread padding evenly arround terminal content
decorations = "None"
resize_increments = false

[scrolling]
history = 0  # disabled

[font]
# normal = { family = "DejaVuSansM Nerd Font", style = "Regular" }
# normal = { family = "JetBrainsMono NF", style = "Regular" }
# normal = { family = "UbuntuMono Nerd Font", style = "Regular" }
normal = { family = "UbuntuSansMono Nerd Font", style = "Regular" }
# normal = { family = "Liberation Mono", style = "Regular" }
# bold = { style = "ExtraBold" }
size = 11.0
# offset = { x = 0, y = -3 } 
# glyph_offset = { x = 0, y = -1 }

[env]
TERM = "alacritty-direct"  # tmux use it to enable true color

[terminal]
shell = "tmux"
