shell = "tmux"

[window]
dimensions = { columns = 80, lines = 24 }
position = "None"
padding = { x = 1, y = 1 }
dynamic_padding = true  # spread padding evenly arround terminal content
decorations = "None"
resize_increments = false

[scrolling]
history = 0  # disabled

[font]
normal = { family = "DejaVuSansM Nerd Font Mono", style = "Regular" }
size = 12.0

[env]
TERM = "alacritty-direct"  # tmux use it to enable true color
