#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

set -x

zig_version=0.15.2
ghostty_version=1.3.1

zig_dir="zig-x86_64-linux-${zig_version}"
zig_archive="${zig_dir}.tar.xz"
zig_release="https://ziglang.org/download/${zig_version}/${zig_archive}"
zig_install_dir="${HOME}/.local/opt/zig"
zig="${HOME}/.local/opt/zig/zig-x86_64-linux-${zig_version}/zig"

ghostty_dir="ghostty-${ghostty_version}"
ghostty_archive="${ghostty_dir}.tar.gz"
ghostty_release="https://release.files.ghostty.org/${ghostty_version}/${ghostty_archive}"
ghostty_install_dir="${HOME}/.local/src"
ghostty_src_dir="${ghostty_install_dir}/${ghostty_dir}"

install_zig() {
	if test -f "${zig}"; then
		echo "[info] ${zig} already exists, skipping zig installation"
		return
	fi

	pushd>/dev/null "$(mktemp -d)" || exit 1

	curl -LO "${zig_release}"
	mkdir -p "${zig_install_dir}"
	tar -C "${zig_install_dir}" -xf "${zig_archive}"

	popd>/dev/null || exit 1
}

# call only once after download
patch_ghostty() {
	patch -d "${ghostty_src_dir}" -p1 <./patches/0001-implement-OSC-4273.patch
}

download_ghostty() {
	if test -d "${ghostty_src_dir}"; then
		echo "[info] ${ghostty_src_dir} already exists, skipping ghostty download"
		return
	fi

	pushd>/dev/null "$(mktemp -d)" || exit 1

	curl -LO "${ghostty_release}"
	mkdir -p "${ghostty_install_dir}"
	# will create ghostty_src_dir
	tar -C "${ghostty_install_dir}" -xf "${ghostty_archive}"

	popd>/dev/null || exit 1

	patch_ghostty
}


install_ghostty() {
	download_ghostty

	pushd "${ghostty_src_dir}" || exit 1

	"${zig}" build -p "${HOME}/.local" -Doptimize=ReleaseFast

	popd>/dev/null || exit 1
}

if [[ "$INSTALL_WITH_SUDO" ]] ; then
  sudo apt-get install -y \
    curl xdotool libgtk4-layer-shell-dev libgraphene-1.0-dev libcairo2-dev libpango1.0-dev \
    libgdk-pixbuf-2.0-dev libadwaita-1-dev libgtk-4-dev
fi


if [[ ! "$CONFIG_ONLY" ]] ; then
  install_zig
  install_ghostty
fi

install_config config.ghostty .config/ghostty/config.ghostty
install_config inc .config/ghostty/inc
install_config shaders/ .config/ghostty/shaders
install_config bin .local/bin

systemctl --user daemon-reload
systemctl --user enable app-com.mitchellh.ghostty.service
systemctl --user start app-com.mitchellh.ghostty.service
