#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

install_wezterm() {
  if [[ "$INSTALL_WITH_SUDO" ]] ; then
    curl -fsSL https://apt.fury.io/wez/gpg.key \
      | sudo gpg --yes --dearmor -o /usr/share/keyrings/wezterm-fury.gpg
    echo 'deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' \
      | sudo tee /etc/apt/sources.list.d/wezterm.list
    sudo chmod 644 /usr/share/keyrings/wezterm-fury.gpg
    sudo apt-get update
    sudo apt-get install -y wezterm
  else
    echo Only sudo install is available for wezterm.
  fi
}

if [[ ! "$CONFIG_ONLY" ]] && ! which wezterm >/dev/null ; then
  install_wezterm
fi

install_config wezterm.lua .config/wezterm/wezterm.lua
install_config themes.lua .config/wezterm/themes.lua
install_config colors .config/wezterm/colors
