alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ..='cd ..'
alias ll='ls -alsFh'
alias la='ls -A'
alias l='ls -CF'
alias go='xdg-open'
alias ip='ip -c=auto'
alias ipa='ip -c=auto -br a'
alias tectonic='tectonic -X'
alias dc='docker compose'
alias dcu='docker compose up -d'
alias dcr='docker compose restart'
alias dcd='docker compose --profile "*" down'
alias dcl='docker compose logs -f --tail=100'
alias dcs='docker compose stop'
alias dcsa='docker compose --profile "*" stop'
alias dcrun='docker compose run --rm'
alias vc='vcs -nsw6 custom --args'
alias lgl='lazygit -sm full log'
alias lg='lazygit'
alias bat='bat -p'
