#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

version() {
  echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'
}

update_delta() {
  if [[ ! "$INSTALL_WITH_SUDO" ]] ; then
    return
  fi

  if which delta >/dev/null ; then
    current_version=$(delta --version | cut -d' ' -f2)
  fi

  repo='dandavison/delta'
  last_version=$(github_release_version "$repo")

  if [[ "$current_version" != "$last_version" ]] ; then
    echo "  download delta ${last_version}..."
    name="${last_version}/git-delta-musl_${last_version}_amd64.deb"
    wget -O/tmp/git-delta.deb "https://github.com/${repo}/releases/download/${name}"
    sudo dpkg -i /tmp/git-delta.deb
  fi
}

install_config gitconfig .gitconfig

if [[ ! "$CONFIG_ONLY" ]] ; then
  update_delta
fi
