#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

version() {
  echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'
}

check_delta_version() {
  if ! which delta >/dev/null ; then
    return 1
  fi

  target=0.17.0
  current=$(delta --version | cut -d' ' -f2)
  [[ $(version $current) -ge $(version $target) ]]
}

install_config gitconfig .gitconfig

if [[ ! "$CONFIG_ONLY" ]] && [[ "$INSTALL_WITH_SUDO" ]] && ! check_delta_version ; then
  wget -O/tmp/git-delta.deb 'https://github.com/dandavison/delta/releases/download/0.17.0/git-delta-musl_0.17.0_amd64.deb'
  sudo dpkg -i /tmp/git-delta.deb
fi
