#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source common.sh

install() {
  dir=$1
  echo -e "\e[01;34mInstall ${dir}\e[00m"
  "${dir}/install" "$backup_dir"
}

install alacritty
install cargo
install clang
install fonts
install fzf
install gdb
install git
install kitty
install nvim
install python
install rofi
install terminator
install tmux
install tools
install vim
install zsh
