#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source common.sh

install() {
  local dir=$1
  shift
  echo -e "\e[01;34mInstall ${dir}\e[00m"
  "${dir}/install" -b "$BACKUP_DIR" "${ARGS[@]}"
}

install tools
install alacritty
install cargo
install clang
install fonts
install fzf
install gdb
install git
install kitty
install nvim
install python
install rofi
install terminator
install tmux
install vim
install zsh
install profile
install lazygit
