#!/bin/bash
backup_dir_model='/tmp/backup_home_XXXXXX'
backup_dir="$(mktemp -d "$backup_dir_model")"

install_with_backup() {
	path_dest="$HOME/$2"
	rsync -a --info=NAME --backup-dir="$backup_dir" "$1" "$path_dest"
}

# cd to script directory
cd "$(dirname "${BASH_SOURCE[0]}")"

echo "backup dir: $backup_dir"
echo "updated files:"

install_with_backup vim/vimrc .vimrc
install_with_backup vim/ycm_extra_conf.py .vim/
install_with_backup vim/colors .vim/
install_with_backup vim/after .vim/
[ -e $HOME/.vim/bundle/Vundle.vim ] \
	|| git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
mkdir -p $HOME/.vim/swapfiles
mkdir -p $HOME/.vim/backup

install_with_backup zsh/zshrc .zshrc
install_with_backup zsh/zsh/ .zsh
install_with_backup zsh/cfyzshprompt/ .cfyzshprompt

install_with_backup gdbinit .gdbinit
install_with_backup gitconfig .gitconfig
