#!/bin/bash
backup_dir_model='/tmp/backup_home_XXXXXX'
backup_dir="$(mktemp -d "$backup_dir_model")"

install_with_backup() {
	path_dest="$HOME/$2"
	rsync -a --info=NAME --backup-dir="$backup_dir" "$1" "$path_dest"
}

# cd to script directory
cd "$(dirname "${BASH_SOURCE[0]}")"

echo "backup dir: $backup_dir"
echo "updated files:"

install_with_backup vim/vimrc .vimrc
install_with_backup vim/ycm_extra_conf.py .vim/ycm_extra_conf.py.off
install_with_backup vim/colors .vim/
install_with_backup vim/after .vim/
install_with_backup vim/syntax .vim/
mkdir -p $HOME/.vim/swapfiles
mkdir -p $HOME/.vim/backup
mkdir -p $HOME/.vim/undodir
mkdir -p $HOME/.config/htop/

install_with_backup zsh/zshrc .zshrc
install_with_backup zsh/zsh/ .zsh
install_with_backup zsh/cfyzshprompt/ .cfyzshprompt

install_with_backup gdbinit .gdbinit
install_with_backup gitconfig .gitconfig
install_with_backup rofi/config.rasi .config/rofi/
install_with_backup htop/htoprc .config/htop/
install_with_backup terminator .config/
install_with_backup nvim .config/
