#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source common.sh

install_nvim() {
	# sudo apt-get install -y python3-venv
	mkdir -p $HOME/.local/share/nvim/sessions
	install_config nvim .config/
}

install_tmux() {
	install_config tmux .config/

	TPM_DIR="${HOME}/.config/tmux/plugins/tpm"
	if test ! -d "${TPM_DIR}"; then
		git clone 'https://github.com/tmux-plugins/tpm' "${HOME}/.config/tmux/plugins/tpm"
		if test -z "${TMUX}"; then
			tmux new "${TPM_DIR}/bindings/install_plugins"
		else
			"${TPM_DIR}/bindings/install_plugins"
		fi
	fi
}

install_zoxide() {
  if ! which zoxide 2>&1 >/dev/null ; then
    curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
  fi
}

install_zsh() {
  zsh_config_dir='.zsh'
  docker_completion_file="${zsh_config_dir}/completion/_docker"

  install_with_backup zsh/zshrc .zshrc
  install_with_backup zsh/zsh/ "${zsh_config_dir}"
  install_with_backup zsh/cfyzshprompt/ .cfyzshprompt

  if [[ ! -r "${docker_completion_file}" ]] ; then
    docker completion zsh >"${HOME}/${docker_completion_file}"
  fi
}

# cd to script directory
cd "$(dirname "${BASH_SOURCE[0]}")"

echo "updated files:"

mkdir -p $HOME/.vim/
install_config vim/vimrc .vimrc
install_config vim/ycm_extra_conf.py .vim/ycm_extra_conf.py.off
install_config vim/colors .vim/
install_config vim/after .vim/
#install_config vim/syntax .vim/
install_config vim/autoload .vim/
mkdir -p $HOME/.vim/swapfiles
mkdir -p $HOME/.vim/backup
mkdir -p $HOME/.vim/undodir
mkdir -p $HOME/.vim/sessions

install_zsh

mkdir -p $HOME/.config/htop/
mkdir -p $HOME/.config/clangd/
install_config gdb/gdbinit .gdbinit
install_config git/gitconfig .gitconfig
install_config rofi/config.rasi .config/rofi/
install_config htop/htoprc .config/htop/
install_config terminator .config/
install_config python/pycodestyle .config/
install_config clang/clangd.yaml .config/clangd/config.yaml
install_config clang/clang-format .clang-format
install_config yapf .config/
install_config fonts .local/share/

install_nvim
install_tmux
install_zoxide

# update fonts
fc-cache
