#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

if [[ ! "$CONFIG_ONLY" ]] && [[ "$INSTALL_WITH_SUDO" ]] && ! which vim >/dev/null ; then
  sudo apt-get install -y vim-gtk3
fi

mkdir -p $HOME/.vim/
mkdir -p $HOME/.vim/swapfiles
mkdir -p $HOME/.vim/backup
mkdir -p $HOME/.vim/undodir
mkdir -p $HOME/.vim/sessions

install_config vimrc .vimrc
#install_config ycm_extra_conf.py .vim/ycm_extra_conf.py.off
install_config colors .vim/colors
install_config after .vim/after
#install_config syntax .vim/syntax
install_config autoload/airline/themes/ese.vim .vim/autoload/airline/themes/ese.vim
