#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

if [[ "$INSTALL_WITH_SUDO" ]] ; then
  pkg_list=$(mktemp)

  dpkg -l | grep 'xfce4-' | tr -s ' ' | cut -d' ' -f2 >"$pkg_list"

  pkgs=()
  for pkg_suffix in battery-plugin cpugraph-plugin systemload-plugin power-manager netload-plugin ; do
    pkg_name="xfce4-$pkg_suffix"
    if ! grep -q "^$pkg_name" "$pkg_list" ; then
      pkgs+=("$pkg_name")
    fi
  done

  if [[ ${#pkgs[@]} -ne 0 ]] ; then
    sudo apt-get install -y ${pkgs[@]}
  fi

  rm -- "$pkg_list"
fi

dir='xfconf/xfce-perchannel-xml'
dst=".config/xfce4/$dir"

install_config "$dir/keyboards.xml" "$dst/keyboards.xml"
install_config "$dir/keyboard-layout.xml" "$dst/keyboard-layout.xml"
install_config "$dir/xfce4-keyboard-shortcuts.xml" "$dst/xfce4-keyboard-shortcuts.xml"
install_config "$dir/xfce4-panel.xml" "$dst/xfce4-panel.xml"
install_config "$dir/xfwm4.xml" "$dst/xfwm4.xml"
install_config "$dir/xsettings.xml" "$dst/xsettings.xml"
