#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

update_nvim() {
  if which nvim >/dev/null ; then
    current_version=$(nvim --version | head -1 | cut -d' ' -f2)
  fi

  repo='neovim/neovim'
  last_version=$(github_release_version "$repo")

  if [[ "$current_version" == "$last_version" ]] ; then
    return
  fi
  
  echo "  download neovim ${last_version}..."
  pushd /tmp >/dev/null
  curl -Lo nvim.tar.gz "https://github.com/${repo}/releases/latest/download/nvim-linux-x86_64.tar.gz"
  
  if [[ "$INSTALL_WITH_SUDO" ]] ; then
	  # Install recent version of node for mason
    curl -fsSL 'https://deb.nodesource.com/setup_23.x' | sudo bash
    sudo apt-get install -y nodejs unzip xclip python3-venv

    sudo rm -rf /opt/nvim
    sudo tar -C /opt -xzf nvim.tar.gz
    sudo ln -sf /opt/nvim-linux-x86_64/bin/nvim /usr/local/bin/nvim
    sudo ln -sf /opt/nvim-linux-x86_64/bin/nvim /usr/local/bin/vi
  else
    tar -C "${HOME}/share" -xzf nvim-linux64.tar.gz
    ln -sfr "${HOME}/share/nvim-linux64/bin/nvim" "${HOME}/.local/bin"
    ln -sfr "${HOME}/share/nvim-linux64/bin/nvim" "${HOME}/.local/bin/vi"
    echo "nvim installed in ${HOME}/.local/bin"
  fi

  rm nvim.tar.gz
  popd >/dev/null
}

mkdir -p $HOME/.config/nvim/
mkdir -p $HOME/.local/share/nvim/sessions

if ! python3 -c 'import venv' ; then
  sudo apt-get install -y python3-venv
fi

if [[ ! "$CONFIG_ONLY" ]] ; then
  update_nvim
fi

install_config after .config/nvim/after
install_config colors .config/nvim/colors
install_config lua .config/nvim/lua
install_config init.lua .config/nvim/init.lua
