#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

mkdir -p "$HOME/.local/share/fonts"

for font in $(find . -name '*.ttf') ; do
  install_config "$font" ".local/share/fonts/$font"
done

fc-cache
