#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

nerdfonts_url='https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0'
fonts_dir="$HOME/.local/share/fonts"

mkdir -p "$fonts_dir"

download() {
  name=$1
  dest_dir="$fonts_dir/$name"

  [[ -d "$dest_dir" ]] && return

  echo "  download fonts: ${name}"
  pushd /tmp >/dev/null
  wget -q "${nerdfonts_url}/${name}.tar.xz"
  mkdir -p "$dest_dir"
  tar -C "$dest_dir" -xf "${name}.tar.xz"
  popd >/dev/null
}

download DejaVuSansMono
download JetBrainsMono
download UbuntuSans
download LiberationMono
download Monaspace
fc-cache
