#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

mkdir -p $HOME/.config/clangd/

install_fzf() {
  if [[ "$INSTALL_WITH_SUDO" ]] ; then
    sudo_cmd='sudo'
    install_dir=/opt/fzf
    bin_link="/usr/local/bin/fzf"
  else
    sudo_cmd=''
    install_dir="${HOME}/share/fzf"
    bin_link="${HOME}/.local/bin/fzf"
    mkdir -p "${install_dir}"
    mkdir -p "${HOME}/.local/bin"
  fi

  ${sudo_cmd} git clone --depth 1 https://github.com/junegunn/fzf.git "${install_dir}"
  ${sudo_cmd} "${install_dir}/install" --bin
  ${sudo_cmd} ln -sfr "${install_dir}/bin/fzf" "${bin_link}"
}

if [[ ! "$CONFIG_ONLY" ]] && ! which fzf >/dev/null ; then
  install_fzf
fi
