#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

mkdir -p $HOME/.config/clangd/

install_fzf() {
  if [[ $(whoami) == 'root' ]] ; then
    sudo_cmd=''
    global_install='y'
  else
    echo -n "Do you want to install nvim using sudo? (if no, install in home dir) [Y/n]: "
    read answer
    if [[ "$answer" != 'n' ]] && [[ "$answer" != 'N' ]] ; then
      sudo_cmd='sudo'
      global_install='y'
    else
      sudo_cmd=''
      global_install='n'
    fi
  fi
  
  if [[ "$global_install" == 'y' ]] ; then
    install_dir=/opt/fzf
    bin_link="/usr/local/bin/fzf"
  else
    install_dir="${HOME}/.local/src/fzf"
    bin_link="${HOME}/.local/bin/fzf"
    mkdir -p "${install_dir}"
    mkdir -p "${HOME}/.local/bin"
  fi

  ${sudo_cmd} git clone --depth 1 https://github.com/junegunn/fzf.git "${install_dir}"
  ${sudo_cmd} "${install_dir}/install" --bin
  ${sudo_cmd} ln -sfr "${install_dir}/bin/fzf" "${bin_link}"
}

if ! which fzf >/dev/null ; then
  install_fzf
fi
