#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

if ! command -v cargo ; then
  sh -- <(curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs) -y
fi

install_config config.toml .cargo/config.toml

source "$HOME/.cargo/env"
cargo install cargo-binstall
