#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

install_podman() {
  source /etc/lsb-release
  if [[ "$DISTRIB_ID" = Ubuntu ]] ; then
    DISTRIB_ID='xUbuntu'
  fi
  export DISTRIB="${DISTRIB_ID}_${DISTRIB_RELEASE}"
  sudo ln -sfr alvistack-prefs /etc/apt/preferences.d/alvistack
  echo "deb http://download.opensuse.org/repositories/home:/alvistack/${DISTRIB}/ /" \
    | sudo tee /etc/apt/sources.list.d/alvistack.list >/dev/null
  curl -fsSL "https://download.opensuse.org/repositories/home:alvistack/${DISTRIB}/Release.key" \
    | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/alvistack.gpg > /dev/null

  sudo apt update
  sudo apt-get install -y podman crun
}

if [[ ! "$CONFIG_ONLY" ]] && [[ "$INSTALL_WITH_SUDO" ]] && ! command -v podman >/dev/null ; then
  install_podman
fi
