#!/bin/bash

declare -A theme=(
  [dark,bg]='#191919'
  [dark,ssh_bg]='#181f1e'
  [dark,window_fg]='#f4ba78'
  [dark,border_fg]='#807688'
  [dark,active_border_fg]='#807688'
  [dark,status_theme]='moon'
  [dark,status_bg]='#3b2956'
  [dark,status_bg_inactive]='#565263'
  [dark,mode]='bg=#4d485c'
  # [dark,cursor]='#f7ba75'
  [dark,blink]='fg=#f7ba75,bg=#333333'
  [dark,palette1]="#535353 #f24b2c #67b121 #e3bf1a #4e85ce #a868b3 #48dfa9 #b6b0aa"
  [dark,palette2]="#7e7e7e #f8887b #93d76f #f6e16b #8caada #cfa2ca #a5f2d4 #fcfcfc"

  [light,bg]='#ffffff'
  [light,ssh_bg]='#f2f2e2'
  [light,window_fg]='#000000'
  [light,border_fg]='#807688'
  [light,active_border_fg]='#807688'
  [light,status_theme]='dawn'
  [light,status_bg]='#ebe5fb'
  [light,status_bg_inactive]='#b4b0c0'
  [light,mode]='bg=#c0bad4'
  # [light,cursor]='#000000'
  [light,blink]='fg=#000000,bg=#bababa'
  [light,palette1]="#bababa #f13714 #58971c #bb7f04 #336bb6 #924f9e #28c78e #494949"
  [light,palette2]="#8b8b8b #9c230d #3a6610 #8b620f #194b8e #5e3166 #0f704d #282828"
)

# insert ":set bg=$1" in running (n)vim-*
change_vim_background() {
  tmux list-panes -aF "#{pane_id} #{pane_pid}" | while read id pid; do
    # check if the given session ID (group of process) contains a vim-like command
    if ps --no-headers -g "${pid}" -o args | grep -Eq '\<(vi|n?vim)([-_].*)?\>'; then
      tmux send-keys -t "${id}" ESCAPE ":set bg=$1" ENTER
    fi
  done
}

set_style() {
  # If the tmux session is started on ssh, it uses a different background
  [[ "$SSH_CLIENT" ]] && theme[$1,bg]="${theme[$1,ssh_bg]}"

  tmux set -g @theme "$1"

  tmux set -g @ese_window_style "fg=${theme[$1,window_fg]},bg=${theme[$1,bg]}"
  tmux set -g @ese_blink_style ${theme[$1,blink]}
  tmux set -g @ese_status_style_inactive "bg=${theme[$1,status_bg_inactive]}"

  tmux set -g @mode_indicator_empty_prompt '#{}'
  tmux set -g @mode_indicator_prefix_mode_style 'bg=#294980,fg=#ffffff'
  tmux set -g @mode_indicator_copy_mode_style 'bg=#9d830b,fg=#ffffff'
  tmux set -g @mode_indicator_sync_mode_style 'bg=#9b3c13,fg=#ffffff'
  tmux set -g @mode_indicator_empty_mode_style 'bg=#574c6b,fg=#dbdbdb'

  tmux set -g @rose_pine_variant "${theme[$1,status_theme]}"  # available: ['main', 'moon', 'dawn']
  tmux set -g @rose_pine_host 'on' # Enables hostname in the status bar
  tmux set -g @rose_pine_hostname_short 'off' # Makes the hostname shorter by using tmux's '#h' format
  tmux set -g @rose_pine_date_time '' # It accepts the date UNIX command format (man date for info)
  tmux set -g @rose_pine_user 'on' # Turn on the username component in the statusbar
  tmux set -g @rose_pine_directory 'on' # Turn on the current folder component in the status bar
  tmux set -g @rose_pine_only_windows 'off' # Leaves only the window module, for max focus and space
  tmux set -g @rose_pine_bar_bg_disable 'on' # Disables background color, for transparent terminal emulators
  tmux set -g @rose_pine_bar_bg_disabled_color_option "${theme[$1,status_bg]}"
  tmux set -g @rose_pine_disable_active_window_menu 'on' # Disables the menu that shows the active window on the left
  tmux set -g @rose_pine_default_window_behavior 'on' # Forces tmux default window list behaviour
  tmux set -g @rose_pine_show_current_program 'on' # Forces tmux to show the current running program as window name
  tmux set -g @rose_pine_show_pane_directory 'on' # Forces tmux to show the current directory as window name
  tmux set -g @rose_pine_status_left_prepend_section '#{tmux_mode_indicator}'
  tmux set -g @rose_pine_status_left_append_section '#{}'

  tmux run '~/.config/tmux/plugins/tmux/rose-pine.tmux'

  tmux set -g window-style "fg=${theme[$1,window_fg]},bg=${theme[$1,bg]}"
  tmux set -g pane-border-style "fg=${theme[$1,border_fg]},bg=${theme[$1,bg]}"
  tmux set -g pane-active-border-style "fg=${theme[$1,active_border_fg]},bg=${theme[$1,bg]}"
  tmux set -g mode-style "${theme[$1,mode]}"
  # tmux set -g cursor-colour "${theme[$1,cursor]}"
  tmux set -g pane-colours "${theme[$1,palette1]} ${theme[$1,palette2]}"

  tmux set -g set-titles on
  tmux set -g set-titles-string "[#S] #W"

  tmux run '~/.config/tmux/plugins/tmux-mode-indicator/mode_indicator.tmux'

  change_vim_background "$1" 
}

case $1 in
  dark)
    set_style dark
    ;;
  light)
    set_style light
    ;;
  *)
  # if theme is not specified, toggle the current one
  window_style=$(tmux show -Av window-style)
  cur_theme=$(tmux show -gv @theme)

  if [[ "$window_style" == 'default' ]] || [[ "$cur_theme" == 'dark' ]] ; then
      set_style light
  else
      set_style dark
  fi
  ;;
esac
