#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

make_install_tmux() {
  src_dir="$HOME/share"
  must_compile=0

  mkdir -p "$src_dir"
  pushd $src_dir >/dev/null

  sudo apt-get install -y \
    libncurses-dev bison gcc make libevent-dev ncurses-dev build-essential pkg-config automake

  if [[ ! -d "./tmux" ]] ; then
    git clone --recursive --depth 1 https://github.com/tmux/tmux.git
    must_compile=1
  else
    git -C tmux remote update
    hash_local="$(git rev-parse @)"
    hash_remote="$(git rev-parse '@{u}')"
    if [[ "${hash_local}" != "${hash_remote}" ]]; then
      git -C tmux pull -r --autostash
    fi
  fi

  if [[ "$must_compile" != 1 ]] ; then
    return
  fi

  pushd tmux >/dev/null
  sh autogen.sh
  ./configure
  make -j14
  sudo make install

  popd >/dev/null
  popd >/dev/null
}

if [[ ! "$CONFIG_ONLY" ]] && [[ "$INSTALL_WITH_SUDO" ]] >/dev/null ; then
  make_install_tmux
fi

mkdir -p $HOME/.config/tmux/
install_config tmux.conf .config/tmux/tmux.conf
install_config ese_theme .config/tmux/ese_theme
install_config scripts .config/tmux/scripts
install_config bin/wrap_esc .local/bin/wrap_esc

TPM_DIR="${HOME}/.config/tmux/plugins/tpm"
if [[ ! -d "${TPM_DIR}" ]] ; then
  git clone 'https://github.com/tmux-plugins/tpm' "${HOME}/.config/tmux/plugins/tpm"
  if [[ -z "${TMUX}" ]] ; then
    tmux new "${TPM_DIR}/bindings/install_plugins"
  else
    "${TPM_DIR}/bindings/install_plugins"
  fi
fi
