#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

mkdir -p $HOME/.config/tmux/

install_config tmux.conf .config/tmux/tmux.conf

TPM_DIR="${HOME}/.config/tmux/plugins/tpm"
if [[ ! -d "${TPM_DIR}" ]] ; then
  git clone 'https://github.com/tmux-plugins/tpm' "${HOME}/.config/tmux/plugins/tpm"
  if [[ -z "${TMUX}" ]] ; then
    tmux new "${TPM_DIR}/bindings/install_plugins"
  else
    "${TPM_DIR}/bindings/install_plugins"
  fi
fi
