#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

make_install_tmux() {
  src_dir="$HOME/.local/src/"

  mkdir -p "$src_dir"
  pushd $src_dir >/dev/null

  apt-get install -y \
    libncurses-dev bison gcc make libevent-dev ncurses-dev build-essential bison pkg-config automake

  if [[ ! -d "./tmux" ]] ; then
    git clone --recursive --depth 1 https://github.com/tmux/tmux.git
  else
    git -C tmux pull
  fi

  pushd tmux >/dev/null
  sh autogen.sh
  ./configure
  make -j14
  make install

  popd >/dev/null
  popd >/dev/null
}

if ! which tmux >/dev/null ; then
  make_install_tmux
fi

mkdir -p $HOME/.config/tmux/
install_config tmux.conf .config/tmux/tmux.conf
install_config ese_theme .config/tmux/ese_theme

TPM_DIR="${HOME}/.config/tmux/plugins/tpm"
if [[ ! -d "${TPM_DIR}" ]] ; then
  git clone 'https://github.com/tmux-plugins/tpm' "${HOME}/.config/tmux/plugins/tpm"
  if [[ -z "${TMUX}" ]] ; then
    tmux new "${TPM_DIR}/bindings/install_plugins"
  else
    "${TPM_DIR}/bindings/install_plugins"
  fi
fi
