#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

mkdir -p "$HOME/.zsh/completion"

zsh_config_dir='.zsh'
docker_completion_file="${zsh_config_dir}/completion/_docker"

install_config zshrc .zshrc
install_config cfg "${zsh_config_dir}/cfg"
install_config cfyzshprompt/ .config/cfyzshprompt

if [[ ! "$CONFIG_ONLY" ]] && [[ "$INSTALL_WITH_SUDO" ]] ; then
  if ! which zsh >/dev/null ; then
    sudo apt-get install -y zsh zsh-syntax-highlighting
  fi

  if ! which cfyze >/dev/null ; then
    sudo apt-get install -y gnupg wget lsb-release apt-transport-https
    wget -O/tmp/install.sh https://pkg.celforyon.fr/dl/install_https.php
    chmod +x /tmp/install.sh
    sudo /tmp/install.sh
    rm /tmp/install.sh
    sudo apt update -y
    sudo apt-get install -y cfyzshprompt-git cfyzshprompt-battery cfyzshprompt-errno
  fi
fi

if which docker >/dev/null && [[ ! -r "${docker_completion_file}" ]] ; then
  docker completion zsh >"${HOME}/${docker_completion_file}"
fi
