#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../common.sh

if ! which zoxide 2>&1 >/dev/null ; then
  curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
fi
